spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev   #
    application:
        name: springCloud-config-lyf-dev
---
spring:
    profiles: test   #Ի
    application:
        name: springCloud-config-lyf-test